# Generated by Django 2.2.3 on 2019-07-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip_address', models.CharField(max_length=100)),
                ('search_value', models.CharField(max_length=200)),
                ('last_search_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_config', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('search_information_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_engine.SearchInformation')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link_to_side', models.TextField()),
                ('position', models.IntegerField()),
                ('count_words', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('search_information_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_engine.SearchInformation')),
            ],
        ),
    ]
