# Generated by Django 2.2.3 on 2019-07-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsearch',
            name='link_to_display',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resultsearch',
            name='count_words',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resultsearch',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultsearch',
            name='link_to_side',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resultsearch',
            name='position',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resultsearch',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='searchconfig',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchconfig',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchinformation',
            name='last_search_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchinformation',
            name='search_value',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='searchinformation',
            name='user_ip_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
