# Generated by Django 2.2.3 on 2019-07-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_auto_20190720_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchconfig',
            name='search_information_fk',
        ),
        migrations.AddField(
            model_name='searchinformation',
            name='search_config_fk',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_engine.SearchConfig'),
        ),
    ]
