# Generated by Django 2.2.3 on 2019-07-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_auto_20190722_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchinformation',
            name='search_config_fk',
        ),
    ]
