# Generated by Django 2.2.3 on 2019-07-23 10:38

from django.db import migrations


def add_config(apps, schema_editor):
    search_config = apps.get_model('search_engine', 'SearchConfig')
    search_config(
        time_config=100
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_remove_searchinformation_search_config_fk'),
    ]

    operations = [
        migrations.RunPython(add_config),
    ]
